#!/usr/bin/env python3
"""Refresh time-sensitive counters and the live repo index in README.md.

Currently maintained:
  * "Sober N days" line — recomputed from SOBRIETY_START.
  * Repository Index (between <!--REPOS:START--> / <!--REPOS:END-->) —
    rebuilt from the live, public, non-fork, non-archived repo list via
    `gh repo list`. Add a repo on GitHub and it shows up here next run;
    nothing here is hand-written or LLM-generated.

To add another counter, append a (pattern, replacement) pair to UPDATERS
below. Each replacement is called with the current README text and must
return the new text.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"

SOBRIETY_START = os.environ.get("SOBRIETY_START", "2023-11-27")
GH_USER = os.environ.get("GH_USER", "thebardchat")
REPOS_START = "<!--REPOS:START-->"
REPOS_END = "<!--REPOS:END-->"


def sober_days(today: date) -> int:
    start = datetime.strptime(SOBRIETY_START, "%Y-%m-%d").date()
    return (today - start).days


def update_sober(text: str, today: date) -> str:
    days = sober_days(today)
    return re.sub(r"Sober\s+\d+\s+days", f"Sober {days} days", text)


def fetch_public_repos() -> list[dict]:
    result = subprocess.run(
        [
            "gh", "repo", "list", GH_USER,
            "--limit", "300",
            "--source", "--no-archived", "--visibility", "public",
            "--json", "name,description,url",
        ],
        capture_output=True, text=True, check=True,
    )
    repos = json.loads(result.stdout)
    return sorted(repos, key=lambda r: r["name"].lower())


def render_repo_table(repos: list[dict]) -> str:
    rows = ["| Repo | Description |", "|------|-------------|"]
    for r in repos:
        desc = (r.get("description") or "").replace("|", "\\|").strip()
        rows.append(f"| [{r['name']}]({r['url']}) | {desc} |")
    return "\n".join(rows)


def update_repo_index(text: str, today: date) -> str:
    if REPOS_START not in text or REPOS_END not in text:
        return text
    repos = fetch_public_repos()
    table = render_repo_table(repos)
    block = (
        f"{REPOS_START}<!-- auto-generated by scripts/update_readme.py "
        f"from the live public repo list; do not hand-edit between markers -->\n"
        f"*{len(repos)} public repos, refreshed {today.isoformat()}*\n\n"
        f"{table}\n"
        f"{REPOS_END}"
    )
    pattern = re.compile(
        re.escape(REPOS_START) + r".*?" + re.escape(REPOS_END), re.DOTALL
    )
    return pattern.sub(lambda _: block, text)


UPDATERS = [update_sober, update_repo_index]


def main() -> int:
    today = date.today()
    text = README.read_text(encoding="utf-8")
    new_text = text
    for fn in UPDATERS:
        new_text = fn(new_text, today)

    if new_text == text:
        print("README already up to date.")
        return 0

    README.write_text(new_text, encoding="utf-8")
    print(f"README updated for {today.isoformat()}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
